### ISSUE TITLE
How to associate existing local account with Etsy account?

### ISSUE THREAD

**Issue by Granga** [anwarhahjjeffersongeorge/passport-etsy#1]
Let's say I have local user account that is already logged in on my app.
```javascript
let user: {
    id: 1,
    email: "user@example.org",
    etsyUserId: undefined
};
```
Next, the user clicks the *Etsy Authorize* button, and completes the authorization.
To be able to associate the local account with the Etsy account, I'll need the local `user.id`. 
Can I access that property anywhere?

For local authentication I use [passport-local](https://github.com/jaredhanson/passport-local).

Thanks.

**Comment by anwarhahjjeffersongeorge** [comment]
I'm not sure how your app works, and I haven't done anything with this for a while, but as I recall, you should be able to get it in the callback from `Strategy.prototype.userProfile` in [strategy.js]( https://github.com/anwarhahjjeffersongeorge/passport-etsy/blob/32158e6ded6973f095a2f061875c2eeed39e4984/dist/strategy.js).

If you successfully authenticated, it will send the the profile to the callback that you provide.
